spring.application.name=PAYMENT_SERVCIE
server.port=5006

# ===============================
# MySQL Connection (UTC)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/salon_payment?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA Settings
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Payment Settings
# ===============================

razorpay.api.key = "raazorpay api key"
razorpay.secret.key = "raazorpay secret key"

stripe.secret.key = "stripe secret key"